# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Text + Media
  description: Text + Media
  icon: 'crop_3_2'
  tags: ['view_column_2']

# Defines the structure of this component, as well as the default values
blueprint:
  text:
  image:
  image_alt:
  reversed: false

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: html
