# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Hero component
  icon: 'crop_3_2'
  tags: ['hero']

# Defines the structure of this component, as well as the default values
blueprint:
  title: Hero title here
  description: Longer hero description here
  image: /images/about/aboutfeature-two.png
  image_alt: Image alt text here
